# Generated by Django 4.0.6 on 2022-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.BigIntegerField(db_column='idUser')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(db_column='apellido_paterno', max_length=50)),
                ('apellido_materno', models.CharField(blank=True, db_column='apellido_materno', max_length=50, null=True)),
            ],
        ),
    ]
