# Generated by Django 4.0.6 on 2022-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddepartamento', models.CharField(db_column='idDepartamento', max_length=8)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
    ]
