# Generated by Django 4.0.6 on 2022-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='iddepartamento',
            field=models.CharField(db_column='idDepartamento', default=1, max_length=8),
            preserve_default=False,
        ),
    ]
